package com.codebasecartographer.api.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Persistent identity for a Local Compute Agent worker.
 * The workerId is generated by the CLI on first install and sent
 * during registration. The server validates ownership (user_id match)
 * on every connection.
 */
@Entity
@Table(name = "local_workers")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LocalWorker {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    // CLI-generated UUID — stable across reconnections
    @Column(name = "worker_id", nullable = false, unique = true)
    private String workerId;

    @Column(name = "user_id", nullable = false)
    private String userId;

    @Column(name = "device_name")
    private String deviceName;

    @Column(name = "cli_version", length = 50)
    private String cliVersion;

    @Column(name = "last_seen_at")
    private LocalDateTime lastSeenAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
